#!/bin/bash

# ------------------------------------------------------------------
#  BSOF/I - Block structured factorization and inversion codes 
#  for CPU+GPU platforms
#  Copyright (c) 2013, Sergiy Gogolenko
#  e-mail: sgogolenk@ucdavis.edu
# ------------------------------------------------------------------
#  Description:
#   Setup config scriph with settings.

SYSTEM=${1:-`uname -n`}
TOP_DIR=`echo "${PWD}" | sed -e 's/\//@/g'`

cat ./config.mk.template |  \
    sed "s/@system@/${SYSTEM}/g;s/@top_dir@/${TOP_DIR}/g;s/@/\//g" \
    > ./config.mk

cat ./bin/sys/submit.py.in |  \
    sed "s/@system@/${SYSTEM}/g;s/@top_dir@/${TOP_DIR}/g;s/@/\//g" \
    > ./bin/sys/submit.py
